apiVersion: v1
kind: Service
metadata:
  name: s1
spec:
  selector:
    app: a1
---
apiVersion: v1
kind: Service
metadata:
  name: s2
spec:
  selector:
    app: a2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: a1
spec:
  selector:
    matchLabels:
      app: a1
  serviceName: s1
  replicas: 1
  template:
    metadata:
      labels:
        app: a1
    spec: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: a2
spec:
  selector:
    matchLabels:
      app: a2
  serviceName: s2
  replicas: 1
  template:
    metadata:
      labels:
        app: a2
    spec: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec: {}
